export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'

export const FETCH_AUCTIONS_COLLECTION = 'FETCH_AUCTIONS_COLLECTION'

export const FETCH_AUCTION_DETAIL = 'FETCH_AUCTION_DETAIL'
export const CLEAR_AUCTION_DETAIL = 'CLEAR_AUCTION_DETAIL'
export const UPDATE_BID_HISTORY = 'UPDATE_BID_HISTORY'
export const UPDATE_AUCTION_COMMENTS = 'UPDATE_AUCTION_COMMENTS'