export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'
export const SHOW_POPUP_AUTH = 'SHOW_POPUP_AUTH'

export const FETCH_AUCTIONS_COLLECTION = 'FETCH_AUCTIONS_COLLECTION'

export const FETCH_AUCTION_DETAIL = 'FETCH_AUCTION_DETAIL'
export const FETCH_AUCTION_COMMENTS = 'FETCH_AUCTION_COMMENTS'
export const CLEAR_AUCTION_DETAIL = 'CLEAR_AUCTION_DETAIL'
export const UPDATE_BID_HISTORY = 'UPDATE_BID_HISTORY'
export const UPDATE_AUCTION_COMMENTS = 'UPDATE_AUCTION_COMMENTS'
export const UPDATE_COMMENT_REP = 'UPDATE_COMMENT_REP'
export const SET_COMMENTS_FILTER = 'SET_COMMENTS_FILTER'

export const FETCH_CATEGORIES_COLLECTION = 'FETCH_CATEGORIES_COLLECTION'